// This file is auto-generated by api/scripts/sync-purchase-units.mjs.
// Do not edit directly.

export const PURCHASE_UNITS = [
	"GRAM",
	"KILOGRAM",
	"MILLILITRE",
	"LITRE",
	"OUNCE",
	"POUND",
	"PINT",
	"PACK",
	"UNIT",
] as const;

export type PurchaseUnit = (typeof PURCHASE_UNITS)[number];
