// This file is auto-generated by api/scripts/sync-units.mjs.
// Do not edit directly.

export const TIME_UNITS = ["SECONDS", "MINUTES", "HOURS", "DAYS"] as const;

export const PURCHASE_UNITS = [
	"GRAM",
	"KILOGRAM",
	"MILLILITRE",
	"LITRE",
	"OUNCE",
	"POUND",
	"PINT",
	"PACK",
	"UNIT",
] as const;

export type TimeUnit = (typeof TIME_UNITS)[number];
export type PurchaseUnit = (typeof PURCHASE_UNITS)[number];
