import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const schemaPath = path.resolve(__dirname, "../prisma/schema.prisma");
const outputPath = path.resolve(__dirname, "../../shared/lib/units.ts");

function extractPrismaEnumValues(schema, enumName) {
	const enumMatch = schema.match(new RegExp(`enum\\s+${enumName}\\s*\\{([\\s\\S]*?)\\}`, "m"));

	if (!enumMatch) {
		throw new Error(`Could not find enum ${enumName} in ${schemaPath}`);
	}

	const values = enumMatch[1]
		.split("\n")
		.map((line) => line.replace(/\/\/.*$/, "").trim())
		.filter(Boolean)
		.map((line) => line.split(/\s+/)[0]);

	if (values.length === 0) {
		throw new Error(`Enum ${enumName} does not contain any values`);
	}

	return values;
}

const schema = await readFile(schemaPath, "utf8");
const timeUnits = extractPrismaEnumValues(schema, "TimeUnit");
const purchaseUnits = extractPrismaEnumValues(schema, "PurchaseUnit");

const output = `// This file is auto-generated by api/scripts/sync-units.mjs.
// Do not edit directly.

export const TIME_UNITS = ${JSON.stringify(timeUnits, null, 2)} as const;

export const PURCHASE_UNITS = ${JSON.stringify(purchaseUnits, null, 2)} as const;

export type TimeUnit = (typeof TIME_UNITS)[number];
export type PurchaseUnit = (typeof PURCHASE_UNITS)[number];
`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${output.trimEnd()}\n`, "utf8");

console.log(
	`Synced ${timeUnits.length} TimeUnit values and ${purchaseUnits.length} PurchaseUnit values to ${path.relative(process.cwd(), outputPath)}`,
);
